[package]
name = "filebridge_core"
version = "0.3.0"
edition = "2021"
license = "MIT"

[lib]
name = "filebridge_core"
crate-type = ["cdylib"]

[dependencies]
# 口令鉴权与管理
sha2 = "0.10"
hmac = "0.12"
# 无第三方 HTTP, 纯 std 手写, 保持体积小

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true